# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c077bb0de2c2c68c6c8e85631e2cc546af785a18cb98dea83d0ea4a019e73d600ba8d11924b6d3ea86dd0c462d237197aab33dacaad9b5818841b3df46378955

test:
  secret_key_base: 048a4cc06a0736c459dbab8e7d067805b48345627c89615fce285b61594d19b4579d98f002af6b279df2f98d3aefea2994626c024ffafae31856e06321c11a2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
